### ISSUE TITLE
listener argument must be a function

### ISSUE THREAD

**Issue by gowridev** [megahertz/howfat#8]
when i try to run the below command i get the error "listener argument must be a function"
npx howfat jasmine 
or
howfat jasmine

please guide me how to resolve this

**Comment by megahertz** [comment]
Could you please run the command with -v flag and post the full results here?

**Comment by gowridev** [comment]
# howfat jasmine -v
get http://registry.npmjs.org/jasmine
Error: TypeError: "listener" argument must be a function
    at ClientRequest.once (events.js:340:11)
    at new ClientRequest (_http_client.js:174:10)
    at request (http.js:39:10)
    at Object.get (http.js:43:13)
    at createHttpStream (/usr/lib/node_modules/howfat/src/utils/http/http.js:88:24)
    at HttpClient.get [as getFunction] (/usr/lib/node_modules/howfat/src/utils/http/http.js:19:23)
    at HttpTask.addTask [as startFunction] (/usr/lib/node_modules/howfat/src/utils/http/HttpClient.js:44:19)
    at HttpTask.start (/usr/lib/node_modules/howfat/src/utils/http/HttpTask.js:43:27)
    at HttpClient.runTask (/usr/lib/node_modules/howfat/src/utils/http/HttpClient.js:142:10)
    at HttpClient.next (/usr/lib/node_modules/howfat/src/utils/http/HttpClient.js:126:10)
[root@inp00990 web_app]#

**Comment by megahertz** [comment]
Thanks, will try to investigate a bit later

**Comment by megahertz** [comment]
It requires node >= 10.9
